function Messenger(win){this.win=win;this.init();}
Messenger.prototype.init=function(){var self=this;var receiver=function(event){if(event.source!=self.win)return;(self.onmessage||function(){}).call(self,event.data);};if(window.addEventListener)
window.addEventListener('message',receiver,false);else if(window.attachEvent)
window.attachEvent('onmessage',receiver);};Messenger.prototype.send=function(data){this.win.postMessage(data,'*');};Messenger.initInParent=function(frame){return new this(frame.contentWindow);};Messenger.initInIframe=function(){return new this(window.parent);};if(!window.postMessage&&window.attachEvent){Messenger.prototype.init=function(){var isSameOrigin=false;try{isSameOrigin=!!this.win.location.href;}catch(ex){}
if(isSameOrigin){this.send=this.sendForSameOrigin;this.initForSameOrigin();return;}
this.queue=[];if(window.parent==this.win){this.initForParent();}else{this.initForFrame();}};Messenger.prototype.initForSameOrigin=function(){var self=this;document.attachEvent('ondataavailable',function(event){if(!event.eventType||event.eventType!=='message'||event.eventSource!=self.win)
return;(self.onmessage||function(){}).call(self,event.eventData);});};Messenger.prototype.sendForSameOrigin=function(data){var self=this;setTimeout(function(){var event=self.win.document.createEventObject();event.eventType='message';event.eventSource=window;event.eventData=data;self.win.document.fireEvent('ondataavailable',event);});};Messenger.prototype.initForParent=function(){var fragment=document.createDocumentFragment();var style='width: 1px; height: 1px; position: absolute; left: -999px; top: -999px;';var senderFrame=document.createElement('iframe');senderFrame.style.cssText=style;fragment.appendChild(senderFrame);var receiverFrame=document.createElement('iframe');receiverFrame.style.cssText=style;fragment.appendChild(receiverFrame);document.body.insertBefore(fragment,document.body.firstChild);this.senderWin=senderFrame.contentWindow;this.receiverWin=receiverFrame.contentWindow;this.startReceive();};Messenger.prototype.initForFrame=function(){this.senderWin=null;this.receiverWin=null;var self=this;this.timerId=setInterval(function(){self.waitForFrame();},50);};Messenger.prototype.waitForFrame=function(){var senderWin;var receiverWin;try{senderWin=this.win[1];receiverWin=this.win[0];}catch(ex){}
if(!senderWin||!receiverWin)return;clearInterval(this.timerId);this.senderWin=senderWin;this.receiverWin=receiverWin;if(this.queue.length)
this.flush();this.startReceive();};Messenger.prototype.startReceive=function(){var self=this;this.timerId=setInterval(function(){self.tryReceive();},50);};Messenger.prototype.tryReceive=function(){try{this.receiverWin.name;return;}catch(ex){}
this.receiverWin.location.replace('about:blank');var self=this;setTimeout(function(){self.receive();},0);};Messenger.prototype.receive=function(){var rawData=null;try{rawData=this.receiverWin.name;}catch(ex){}
if(!rawData)return;this.receiverWin.name='';var self=this;var dataList=rawData.substring(1).split('|');for(var i=0;i<dataList.length;i++)(function(){var data=decodeURIComponent(dataList[i]);setTimeout(function(){(self.onmessage||function(){}).call(self,data);},0);})();};Messenger.prototype.send=function(data){this.queue.push(data);if(!this.senderWin)return;this.flush();};Messenger.prototype.flush=function(){var dataList=[];for(var i=0;i<this.queue.length;i++)
dataList[i]=encodeURIComponent(this.queue[i]);var encodedData='|'+dataList.join('|');try{this.senderWin.name+=encodedData;this.queue.length=0;}catch(ex){this.senderWin.location.replace('about:blank');var self=this;setTimeout(function(){self.flush();},0);}};};(function(global){var $=global.$;var IFRAME_STYLE=['border: none;','border-radius: 10px;','left: 50%;','height: 417px;','margin: -215px 0 0 -208px;','position: fixed;','top: 50%;','width: 434px;'].join('');var CTN_STYLE=['background: #4C4C4C;','background: url(http://img.wdjimg.com/account/overlay.png);','background: rgba(0, 0, 0, .7);','bottom: 0;','left: 0;','position: fixed;','right: 0;','top: 0;','z-index: 999;'].join('');var AccountHook={};AccountHook.open=function(options,context){options=options||{};options.name=options.name||'';options.callback=options.callback||function(){return;};if(!global.Messenger||options.popup===false){global.document.location.href='http://www.wandoujia.com/account/web.html?callback='+encodeURIComponent(global.document.location.href)+'#'+options.name;return;}
var $ctn=$('<div>').attr('style',CTN_STYLE).appendTo('body');var $iframe=$('<iframe>').attr({src:'http://www.wandoujia.com/account/?source=web&close=1#'+options.name,style:IFRAME_STYLE}).appendTo($ctn);var messenger=global.Messenger.initInParent($iframe[0]);messenger.onmessage=function(message){var msg=message.split(':'),data=decodeURIComponent(msg[1]);switch(msg[0]){case'height':if(navigator.userAgent.toLowerCase().indexOf('msie')>-1){data=Number(data)+4;}
$iframe.css('height',data+'px');break;case'close':$ctn.remove();break;case'done':$ctn.remove();options.callback.call(context||global);break;case'redirect':global.document.location.href=data;break;}};$ctn.on('click',function(){$ctn.remove();});};var SnapPea=global.SnapPea||{};SnapPea.AccountHook=AccountHook;global.SnapPea=SnapPea;}(this));;(function(global){var Deferred=window.Q.defer;var ajax=window.$.ajax;if($.ajaxSetup){$.ajaxSetup({xhrFields:{withCredentials:true}});}
var extend=function(dist,source){if(!source){return dist;}
var prop;for(prop in source){if(source.hasOwnProperty(prop)){dist[prop]=source[prop];}}
return dist;};var HOST='https://account.wandoujia.com',HOST_HTTP='http://www.wandoujia.com/api/account',API_VERSION_4='/v4/api',USE_HTTP_API=navigator.userAgent.toLowerCase().indexOf('msie')>-1,PREFIX=(USE_HTTP_API?HOST_HTTP:HOST)+API_VERSION_4;var CONFIG={login:PREFIX+'/login',logout:PREFIX+'/logout',captcha:PREFIX+'/seccode',reg:PREFIX+'/register',checkUsername:PREFIX+'/isUsernameExisted',checkUserLogin:PREFIX+'/profile',findPwd:PREFIX+'/findpassword',checkCode:PREFIX+'/checkcode',resetPwd:PREFIX+'/resetpassword',modifyPwd:PREFIX+'/profile/password',checkPasscode:PREFIX+'/checkpasscode',modifyPwdByCode:PREFIX+'/modifypassword',completeProfile:PREFIX+'/completeProfile',unbindThirdParty:PREFIX+'/social/unbind',avatar:PREFIX+'/avatar'};var CONFIG_WEB={loginWithThirdParty:HOST+'/web/oauth2/{1}/login'};var USER_INFO;var IS_LOGINED=false;var Account={};Account.CAPTCHA=CONFIG.captcha;Account.loginAsync=function(data,options){var deferred=new Deferred();data=data||{};options=options||{};if(!data.username||!data.password){deferred.reject({error:-2,msg:'参数不全'});}else{ajax({type:'POST',dataType:'json',url:CONFIG.login,data:extend({username:data.username,password:data.password,seccode:data.seccode||''},options),success:function(resp){if(resp.error===0){IS_LOGINED=true;USER_INFO=resp.member;deferred.resolve(resp.member);}else{deferred.reject(resp);}},error:function(xhr){if(xhr.readyState===4){deferred.reject(xhr.responseJSON);}
deferred.reject({error:-1,msg:'请求失败，请检查网络连接状况。'});}});}
return deferred.promise;};Account.isLogined=function(){return IS_LOGINED;};Account.getUserInfo=function(){return USER_INFO;};Account.logoutAsync=function(options){var deferred=new Deferred();options=options||{};ajax({type:'POST',dataType:'json',url:CONFIG.logout,data:options,success:function(resp){if(resp.error===0){IS_LOGINED=false;USER_INFO=undefined;deferred.resolve(resp);}else{deferred.reject(resp);}},error:function(xhr){if(xhr.readyState===4){deferred.reject(xhr.responseJSON);}
deferred.reject({error:-1,msg:'请求失败，请检查网络连接状况。'});}});return deferred.promise;};Account.regAsync=function(data,options){var deferred=new Deferred();data=data||{};options=options||{};if(!data.username||!data.password){deferred.reject({error:-2,msg:'参数不全'});}else{ajax({type:'POST',dataType:'json',url:CONFIG.reg,data:extend({username:data.username,password:data.password,nick:data.nickname||'',seccode:data.seccode||''},options),success:function(resp){if(resp.error===0){IS_LOGINED=true;USER_INFO=resp.member;deferred.resolve(resp.member);}else{deferred.reject(resp);}},error:function(xhr){if(xhr.readyState===4){deferred.reject(xhr.responseJSON);}
deferred.reject({error:-1,msg:'请求失败，请检查网络连接状况。'});}});}
return deferred.promise;};Account.checkUsernameAsync=function(username,options){var deferred=new Deferred();options=options||{};if(username===undefined){deferred.reject({error:-2,msg:'参数不全'});}else{ajax({type:'POST',dataType:'json',url:CONFIG.checkUsername,data:extend({username:username},options),success:function(resp){deferred.resolve(resp);},error:function(xhr){if(xhr.readyState===4){deferred.reject(xhr.responseJSON);}
deferred.reject({error:-1,msg:'请求失败，请检查网络连接状况。'});}});}
return deferred.promise;};Account.checkUserLoginAsync=function(options){var deferred=new Deferred();options=options||{};var jsonp=!!options.jsonp;delete options.jsonp;ajax({type:'GET',dataType:jsonp?'jsonp':'json',url:CONFIG.checkUserLogin,data:options,crossDomain:jsonp?true:undefined,success:function(resp){if(resp.error===0){IS_LOGINED=true;USER_INFO=resp.member;deferred.resolve(true);}else{IS_LOGINED=false;USER_INFO=undefined;deferred.reject(false);}},error:function(){deferred.reject(false);}});return deferred.promise;};Account.findPwdAsync=function(username,options){var deferred=new Deferred();options=options||{};if(username===undefined){deferred.reject({error:-2,msg:'参数不全'});}else{ajax({type:'POST',dataType:'json',url:CONFIG.findPwd,data:extend({username:username},options),success:function(resp){if(resp.error===0){deferred.resolve(resp);}else{deferred.reject(resp);}},error:function(xhr){if(xhr.readyState===4){deferred.reject(xhr.responseJSON);}
deferred.reject({error:-1,msg:'请求失败，请检查网络连接状况。'});}});}
return deferred.promise;};Account.checkCodeAsync=function(data,options){var deferred=new Deferred();data=data||{};options=options||{};if(data.username===undefined||data.passcode===undefined){deferred.reject({error:-2,msg:'参数不全'});}else{ajax({type:'POST',dataType:'json',url:CONFIG.checkCode,data:extend({username:data.username,passcode:data.passcode},options),success:function(resp){if(resp.error===0){deferred.resolve(resp);}else{deferred.reject(resp);}},error:function(xhr){if(xhr.readyState===4){deferred.reject(xhr.responseJSON);}
deferred.reject({error:-1,msg:'请求失败，请检查网络连接状况。'});}});}
return deferred.promise;};Account.resetPwdAsync=function(data,options){var deferred=new Deferred();data=data||{};options=options||{};if(data.username===undefined||data.passcode===undefined||data.password===undefined){deferred.reject({error:-2,msg:'参数不全'});}else{ajax({type:'POST',dataType:'json',url:CONFIG.resetPwd,data:extend({username:data.username,passcode:data.passcode,password:data.password,repeatedpassword:data.password},options),success:function(resp){if(resp.error===0){deferred.resolve(resp);}else{deferred.reject(resp);}},error:function(xhr){if(xhr.readyState===4){deferred.reject(xhr.responseJSON);}
deferred.reject({error:-1,msg:'请求失败，请检查网络连接状况。'});}});}
return deferred.promise;};Account.modifyPwdAsync=function(data,options){var deferred=new Deferred();data=data||{};options=options||{};if(data.password===undefined||data.newpassword===undefined){deferred.reject({error:-2,msg:'参数不全'});}else{ajax({type:'POST',dataType:'json',url:CONFIG.modifyPwd,data:extend({oldpassword:data.password,newpassword:data.newpassword},options),success:function(resp){if(resp.error===0){deferred.resolve(resp);}else{deferred.reject(resp);}},error:function(xhr){if(xhr.readyState===4){deferred.reject(xhr.responseJSON);}
deferred.reject({error:-1,msg:'请求失败，请检查网络连接状况。'});}});}
return deferred.promise;};Account.checkPasscodeAsync=function(data,options){var deferred=new Deferred();data=data||{};options=options||{};if(data.passcode===undefined){deferred.reject({error:-2,msg:'参数不全'});}else{ajax({type:'POST',dataType:'json',url:CONFIG.checkPasscode,data:extend({passcode:data.passcode},options),success:function(resp){if(resp.error===0){deferred.resolve(resp);}else{deferred.reject(resp);}},error:function(xhr){if(xhr.readyState===4){deferred.reject(xhr.responseJSON);}
deferred.reject({error:-1,msg:'请求失败，请检查网络连接状况。'});}});}
return deferred.promise;};Account.modifyPwdByCodeAsync=function(data,options){var deferred=new Deferred();data=data||{};options=options||{};if(data.passcode===undefined||data.password===undefined){deferred.reject({error:-2,msg:'参数不全'});}else{ajax({type:'POST',dataType:'json',url:CONFIG.modifyPwdByCode,data:extend({passcode:data.passcode,password:data.password},options),success:function(resp){if(resp.error===0){deferred.resolve(resp);}else{deferred.reject(resp);}},error:function(xhr){if(xhr.readyState===4){deferred.reject(xhr.responseJSON);}
deferred.reject({error:-1,msg:'请求失败，请检查网络连接状况。'});}});}
return deferred.promise;};Account.updateProfileAsync=function(data,options){var deferred=new Deferred();data=data||{};options=options||{};if(data.nickname===undefined){deferred.reject({error:-2,msg:'参数不全'});}else{ajax({type:'POST',dataType:'json',url:CONFIG.completeProfile,data:extend({nick:data.nickname},options),success:function(resp){if(resp.error===0){USER_INFO=resp.member;deferred.resolve(resp.member);}else{deferred.reject(resp);}},error:function(xhr){if(xhr.readyState===4){deferred.reject(xhr.responseJSON);}
deferred.reject({error:-1,msg:'请求失败，请检查网络连接状况。'});}});}
return deferred.promise;};Account.uploadAvatarAsync=function(data,options){var deferred=new Deferred();data=data||{};options=options||{};var formData,f;if(data.file===undefined){deferred.reject({error:-2,msg:'参数不全'});}else{formData=new global.FormData();formData.append('file',data.file);for(f in options){if(options.hasOwnProperty(f)){formData.append(f,options[f]);}}
ajax({type:'POST',dataType:'json',url:CONFIG.avatar,data:formData,processData:false,contentType:false,success:function(resp){if(resp.error===0){USER_INFO=resp.member;deferred.resolve(resp.member.avatar);}else{deferred.reject(resp);}},error:function(xhr){if(xhr.readyState===4){deferred.reject(xhr.responseJSON);}
deferred.reject({error:-1,msg:'请求失败，请检查网络连接状况。'});}});}
return deferred.promise;};Account.unbindThirdPartyAsync=function(data,options){var deferred=new Deferred();data=data||{};options=options||{};var platforms={weibo:'1',sina:'1',qq:'2',renren:'3'};if(data.platform===undefined||platforms[data.platform]===undefined){deferred.reject({error:-2,msg:'参数不全'});}else{ajax({type:'POST',dataType:'json',url:CONFIG.unbindThirdParty,data:extend({platid:platforms[data.platform]},options),success:function(resp){if(resp.error===0){deferred.resolve(resp);}else{deferred.reject(resp);}},error:function(xhr){if(xhr.readyState===4){deferred.reject(xhr.responseJSON);}
deferred.reject({error:-1,msg:'请求失败，请检查网络连接状况。'});}});}
return deferred.promise;};Account.isEmail=function(input){var EMAIL_PATTREN=/^[A-Za-z0-9](([_\.\-]?[a-zA-Z0-9]+)*)@([A-Za-z0-9]+)(([\.\-]?[a-zA-Z0-9]+)*)\.([A-Za-z]{2,})$/;return EMAIL_PATTREN.test(input);};Account.isPhoneNumber=function(input){var PHONE_PATTERN=/^(1(([3548][\d])))\d{8}$/;return PHONE_PATTERN.test(input);};Account.loginWithThirdParty=function(options){options=options||{};options.callback=options.callback||'http://www.wandoujia.com/';var platforms={weibo:'sina',sina:'sina',renren:'renren',qq:'qq'};var platform=platforms[options.platform];delete options.platform;var onclose=options.onclose||function(){return;};delete options.onclose;var datas=[];var d;for(d in options){if(options.hasOwnProperty(d)){datas.push(d+'='+global.encodeURIComponent(options[d]));}}
var targetURL=CONFIG_WEB.loginWithThirdParty.replace('{1}',platform);if(datas.length>0){targetURL=targetURL+'?'+datas.join('&');}
if(options.popup){var win=window.open(targetURL,'loginWithThirdParty','width=650, height=480');var winInterval=setInterval(function(){if(win.closed){clearInterval(winInterval);onclose.call(this);}},200);}else{global.location.href=targetURL;}};var SnapPea=global.SnapPea||{};SnapPea.Account=Account;global.SnapPea=SnapPea;}(this));;(function(){$(document).ready(function(){SnapPea.Account.checkUserLoginAsync({jsonp:!!($.browser.msie&&$.browser.version.split(".")[0]<7)}).then(function(){DeviceCenter._signScanner.publish('ready');}).fail(function(){DeviceCenter._signScanner.publish('welcome');});$('body').on('click','.login-button',function(e){e.preventDefault();SnapPea.AccountHook.open({name:'login',popup:!($.browser.msie&&$.browser.version.split(".")[0]<7),callback:function(){SnapPea.Account.checkUserLoginAsync({jsonp:!!($.browser.msie&&$.browser.version.split(".")[0]<7)}).then(function(){DeviceCenter._signScanner.publish('ready');if(typeof window.updateUserStatus==='function'){window.updateUserStatus();}}).fail(function(){});}});});});})();